// actionTypes.js
export const SET_MENSAJES_DATA = 'SET_MENSAJES_DATA';
export const SET_CUALIFICADOS_DATA = 'SET_CUALIFICADOS_DATA';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PUESTOS = 'SET_PUESTOS';
export const SET_CONEXIONES_DATA = 'SET_CONEXIONES_DATA';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_INVITACIONES_DATA = 'SET_INVITACIONES_DATA';
export const LOAD_LOCALSTORAGE_DATA = 'LOAD_LOCALSTORAGE_DATA';
export const ACTUALIZAR_POSICIONES = 'ACTUALIZAR_POSICIONES';
export const TRANSFER_OK = 'TRANSFER_OK';
export const SET_MES = 'SET_MES';
export const NOMBRE_CUENTA = 'NOMBRE_CUENTA'
export const SET_MENSAJES_NEW = 'SET_MENSAJES_NEW'
export const NOMBRE_CUENTA_BORRAR = "NOMBRE_CUENTA_BORRAR";
export const SET_CUSTOMIZACIONES = 'SET_CUSTOMIZACIONES'