// actionTypes.js
export const SET_MENSAJES_DATA = 'SET_MENSAJES_DATA';
export const SET_CUALIFICADOS_DATA = 'SET_CUALIFICADOS_DATA';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PUESTOS = 'SET_PUESTOS';
export const SET_CONEXIONES_DATA = 'SET_CONEXIONES_DATA';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_INVITACIONES_DATA = 'SET_INVITACIONES_DATA';
export const LOAD_LOCALSTORAGE_DATA = 'LOAD_LOCALSTORAGE_DATA';
export const ACTUALIZAR_POSICIONES = 'ACTUALIZAR_POSICIONES'
